/** @format */

export const datas = [
    {
        id: 1,
        username: "Mark Webber",
        avatar: "/images/avatar-mark-webber.webp",
        messageText: "reacted to your recent post",
        boldedtext: "My first tournament today!",
        mediaSent: null,
        replyText: null,
        groupName: null,
        timePosted: "1m",
        isRead: true,
    },
    {
        id: 2,
        username: "Angela Gray",
        avatar: "/images/avatar-angela-gray.webp",
        messageText: "followed you",
        boldedtext: null,
        replyText: null,
        mediaSent: null,
        groupName: null,
        timePosted: "1 day",
        isRead: true,
    },
    {
        id: 3,
        username: "Jacob Thompson",
        avatar: "/images/avatar-jacob-thompson.webp",
        messageText: "has joined your group",
        boldedtext: null,
        replyText: null,
        mediaSent: null,
        groupName: "Chess Club",
        timePosted: "5m",
        isRead: true,
    },
    {
        id: 4,
        username: "Rizky Hasanuddin",
        avatar: "/images/avatar-rizky-hasanuddin.webp",
        messageText: "sent you a private message",
        boldedtext: null,
        replyText:
            "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
        mediaSent: null,
        groupName: null,
        timePosted: "5 days",
        isRead: false,
    },
    {
        id: 5,
        username: "Kimberly Smith",
        avatar: "/images/avatar-kimberly-smith.webp",
        messageText: "commented on your picture",
        replyText: null,
        boldedtext: null,
        mediaSent: "/images/image-chess.webp",
        groupName: null,
        timePosted: "1 weeks",
        isRead: false,
    },
    {
        id: 6,
        username: "Nathan Peterson",
        avatar: "/images/avatar-nathan-peterson.webp",
        messageText: "reacted to your recent post",
        boldedtext: "5 end-game strategies to increase your win rate",
        replyText: null,
        mediaSent: null,
        groupName: null,
        timePosted: "2 weeks",
        isRead: false,
    },
    {
        id: 7,
        username: "Anna Kim",
        avatar: "/images/avatar-anna-kim.webp",
        messageText: "left the group",
        boldedtext: null,
        replyText: null,
        mediaSent: null,
        groupName: "Chess Club",
        timePosted: "2 weeks",
        isRead: false,
    },
];
